# Generated by Django 3.1.5 on 2021-01-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210117_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
    ]
