# Generated by Django 3.1.5 on 2021-01-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210117_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='car',
        ),
    ]
